# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty
language: cpp

# Disable the default submodule logic
git:
  submodules: false

# Configuration matrix
matrix:
  include:
    - compiler: gcc
      env:
        - CXX_COMPILER=g++-4.9
        - CC_COMPILER=gcc-4.9
        - FC_COMPILER=gfortran-4.9
        - OMPI_CC=gcc-4.9
        - OMPI_FC=gfortran-4.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - gfortran-4.9
            - ant
            - ant-optional
            - cabal-install
            - ghc

# Save shellcheck installation in cache
cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.stack

# Fetch submodule for omni-compiler repository and install dependencies
before_install:
  - git submodule init
  - git submodule update
  - travis_retry sudo apt-get install -qq openmpi-bin libopenmpi-dev
  - cabal update && cabal install ShellCheck
  - export PATH=$PATH:$HOME/.cabal/bin
  - shellcheck --version

# Export compiler variables
before_script:
  - export FC=$FC_COMPILER
  - export CC=$CC_COMPILER
  - export CXX=$CXX_COMPILER
  - export OMPI_CC
  - export OMPI_FC

# Build CLAW FORTRAN Compiler and execute the test suite
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=$HOME/claw .. && make
  - make
  - make install
  - make clean-transformation transformation test
  - cd -
  - ./scripts/check_license # Check license header in sources files
  - cd scripts
  - ./run.shellcheck        # Check shell scripts with shellcheck

# Notification settings
notifications:
  slack: meteoswiss-apn:FFUYLitE3BsncqECl4RqlfHP
  email:
    on_success: never
    on_failure: always
