# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty
group: deprecated-2017Q2 # Until we can use new image
language: cpp

# Disable the default submodule logic
git:
  submodules: false

# Configuration matrix
matrix:
  include:
    - compiler: gcc
      env:
        - CXX_COMPILER=g++-4.9
        - CC_COMPILER=gcc-4.9
        - FC_COMPILER=gfortran-4.9
        - OMPI_CC=gcc-4.9
        - OMPI_FC=gfortran-4.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            #- debian-sid
          packages:
            - gcc-4.9
            - g++-4.9
            - gfortran-4.9
            - ant

# Fetch submodule for omni-compiler repository and install dependencies
before_install:
  - git submodule init
  - git submodule update
  - echo "deb http://archive.ubuntu.com/ubuntu/ wily universe" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -q
  - travis_retry sudo apt-get install -qq openmpi-bin libopenmpi-dev

# Export compiler variables
before_script:
  - export FC=$FC_COMPILER
  - export CC=$CC_COMPILER
  - export CXX=$CXX_COMPILER
  - export OMPI_CC
  - export OMPI_FC

# Build CLAW FORTRAN Compiler and execute the test suite
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=$HOME/claw .. && make
  - make
  - make install
  - make clean-transformation transformation test
  - cd -
#  - cd scripts
#  - ./run.shellcheck # Check shell scripts with shellcheck
# disable until shellcheck 0.4.5 available

# Notification settings
notifications:
  slack: meteoswiss-apn:FFUYLitE3BsncqECl4RqlfHP
  email:
    on_success: never
    on_failure: always
