# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty
group: deprecated-2017Q2 # Until we can use new image
language: cpp

# Disable the default submodule logic
git:
  submodules: false

# Configuration matrix
matrix:
  include:
    - compiler: gcc
      env:
        - CXX_COMPILER=g++-4.9
        - CC_COMPILER=gcc-4.9
        - FC_COMPILER=gfortran-4.9
        - OMPI_CC=gfortran-4.9
        - OMPI_FC=gcc-4.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            #- debian-sid
          packages:
            - gcc-4.9
            - g++-4.9
            - gfortran-4.9
            - ant

# Fetch submodule for omni-compiler repository
before_install:
  - git submodule init
  - git submodule update

install:
  - travis_retry sudo apt-get install -qq openmpi-bin libopenmpi-dev
  - export PATH=$PATH:/usr/lib/openmpi/bin

# Install OpenMPI for OMNI Compiler
before_script:
  - export FC=$FC_COMPILER
  - export CC=$CC_COMPILER
  - export CXX=$CXX_COMPILER
  - export OMPI_CC
  - export OMPI_FC
  #- pushd $(pwd)
  #- wget --no-check-certificate https://www.open-mpi.org/software/ompi/v2.0/downloads/openmpi-2.0.1.tar.gz
  #- tar -zxf openmpi-2.0.1.tar.gz
  #- cd openmpi-2.0.1
  #- sh ./configure --prefix=$HOME/openmpi > /dev/null
  #- make -j > /dev/null
  #- sudo make install > /dev/null
  #- export PATH=$PATH:$HOME/openmpi/bin
  #- popd

# Build CLAW FORTRAN Compiler and execute the test suite
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=$HOME/claw .. && make
  - make
  - make install
  - make clean-transformation transformation test
  - cd -
  - cd scripts
  - ./run.shellcheck # Check shell scripts with shellcheck

# Notification settings
notifications:
  slack: meteoswiss-apn:FFUYLitE3BsncqECl4RqlfHP
  email:
    on_success: never
    on_failure: always
