# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty
language: cpp

# Conifguration matrix
matrix:
  include:
    - compiler: gcc
      env:
        - CXX_COMPILER=g++-4.9
        - CC_COMPILER=gcc-4.9
        - FC_COMPILER=gfortran-4.9
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages:
            - gcc-4.9
            - g++-4.9
            - gfortran-4.9


script:
  - mkdir build
  - cd build
  - FC=$FC_COMPILER CC=$CC_COMPILER CXX=$CXX_COMPILER cmake .. && make
  - make clean-transformation transformation test
